// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBiPgk__H0r7_EtBM-cgVPUAa-v52VzOk',
    appId: '1:823905701039:web:9fb0149964ea84386e985a',
    messagingSenderId: '823905701039',
    projectId: 'stray-dog-reporter',
    authDomain: 'stray-dog-reporter.firebaseapp.com',
    storageBucket: 'stray-dog-reporter.appspot.com',
    measurementId: 'G-V3SHXCTCLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzqByXPaEReal6mAJJoNM3BK6zmIb5yF4',
    appId: '1:823905701039:android:2005fc956875de626e985a',
    messagingSenderId: '823905701039',
    projectId: 'stray-dog-reporter',
    storageBucket: 'stray-dog-reporter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9bP0TV5AV_b7-eRZKlXVO4RlUGY6UlCU',
    appId: '1:823905701039:ios:0101f18f57a7ed116e985a',
    messagingSenderId: '823905701039',
    projectId: 'stray-dog-reporter',
    storageBucket: 'stray-dog-reporter.appspot.com',
    iosBundleId: 'com.example.strayDogReporter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9bP0TV5AV_b7-eRZKlXVO4RlUGY6UlCU',
    appId: '1:823905701039:ios:adfa83adc76a75eb6e985a',
    messagingSenderId: '823905701039',
    projectId: 'stray-dog-reporter',
    storageBucket: 'stray-dog-reporter.appspot.com',
    iosBundleId: 'com.example.strayDogReporter.RunnerTests',
  );
}
